feat: UP-4375 - adding/removing community members
AmityCo/Amity-Social-Cloud-React-Native-Sample-App pull request #6
Opened 2021-08-29 15:48 UTC by ramyareye

2022-03-14 10:47 UTC, y-nk approved these changes

2022-10-19 08:08 UTC, Cijin requested changes

2022-10-19 08:08 UTC, Cijin commented on src/components/AddCommunityMember/index.tsx
> +    setUserId('');
that is the default right? Why set it to empty again?

2022-10-19 08:26 UTC, Cijin approved these changes

2022-10-19 08:27 UTC, merged

2022-11-09 03:21 UTC, y-nk commented
@Cijin @Va1tra could you guys please remove me from the reviewers 😂 ? thanks a lot.